<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="Lucivan Max" content="Comparing V1.0">   
    <link rel="icon"  type="image/png" href="../image/fav_vit.png">
   <title> Comparing </title>

	    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet" media="screen">
    
    <!-- print CSS --> 
    <link href="/css/print.css"  rel="stylesheet" media="print">

    <!-- Custom styles for this template -->
    <link href="/css/jumbotron.css" rel="stylesheet" media="screen">
    
     <!-- Counter CSS -->
    <link href="/css/counter.css" rel="stylesheet" >
    
    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
      </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
      <a class="navbar-brand" >
                <a class="navbar-brand" href="/auth/logout">SAIR</a>           
         </div>  
     	  <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
           
        	  
            </ul>
         </div><!--/.nav-collapse -->
		</div>
    </div>

     <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
         <h4 id="relogio"></h4>
      <h2>COMPARING </h2>
       <h2>Sistema em Manutenção</h2>
      <h4>Tempo estimado para retorno: 00:60 minutos</h4>
        </div>
    </div>

    <div class="container">

		       
      <hr>

       <footer>
   	<p>Você está em um ambiente seguro. Todos os seus dados estão protegidos.</p>
    	 <p> Viterativa - Web e Vídeo Conteúdo CNPJ: XXXXXXXX</p>
       <p>Comparing V1.0 &copy; 2014 - Todos os direitos reservados.</p>
      </footer>
    </div> <!-- /container -->
 <!--  
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/js/jquery-1.11.1.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/relogio.js"></script> 

   </body>
</html>
