<!DOCTYPE html>
<html lang="en">
  <head>	
       <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="Lucivan Max" content="Comparing V1.0">   
    <link rel="icon"  type="image/png" href="../image/fav_vit.png">
   <title> Comparing </title>

       
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/jumbotron.css" rel="stylesheet">
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand"></a>
        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form" action="<?php echo $this->url(array('controller' => 'Auth', 
						'action' => 'login')) ?>" method="post">
            <div class="form-group">
              <input type="text" placeholder="Login" required="" name="login" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Senha" required="" name="senha" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Entrar</button>
          </form>
        </div>
      </div>
    <p class="text-center"> <strong class="text-danger"><?php echo ( sizeof( $this->messages ) > 0 ) ? $this->messages[0] : ""; ?> </strong></p>
    </div>
    <div class="jumbotron">
        <div class="container">
            <h4 id="relogio"></h4>
	       <h2>COMPARING 1.0</h2>
         <div class="row">
		         	<div class="col-md-6">
       		 <p>Sistema Privado de Gestão Multimídia</p>
          	 </div>
		   	 </div>
      </div>
    </div>
         <div class="container">
      <div class="row">
      
      </div>

      <hr>

      <footer> 
      <p> Viterativa - Web e Vídeo Conteúdo CNPJ: XXXXXXXX</p>
       <p>Comparing V1.0 &copy; 2014 - Todos os direitos reservados.</p>
      </footer>
    </div> <!-- /container -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <script src="/js/jquery-1.11.1.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/relogio.js"></script> 
  </body>
</html>
