<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="Lucivan Max" content="Comparing V1.0">   
    <link rel="icon"  type="image/png" href="../image/fav_vit.png">
   <title> Comparing </title>

        <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/jumbotron.css" rel="stylesheet">

	 <!-- Counter CSS -->
    <link href="/css/counter.css" rel="stylesheet" >

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
      </head>

  <body>

     <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <a class="navbar-brand" href=""></a>
<!--     <a class="navbar-brand" href="/admin">VOLTAR</a>  -->        
        </div>  
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
      <!--            <li><a href="/admin">VOLTAR</a></li>
      	<li  class="active"><a href="">Adicionar Vídeo</a></li>   -->
             	<li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">MENU <b class="caret"></b></a>
                <ul class="dropdown-menu">
                 <li class="divider"></li>
                 <li><a href="/admin">Voltar</a></li>
                 <li class="divider"></li>
                  <li class="dropdown-header">MULTIMÍDIA</li>
                  <li><a href="newvideo">Novo Arquivo</a></li>
                  <li><a href="listvideo">Editar/Deletar Arquivo</a></li>
 			<!--   <li><a href="#">Something else here</a></li>  -->
                  <li class="divider"></li>
                  <li class="dropdown-header">USUÁRIOS</li>
                 <li><a href="newuser">Novo Usuário</a></li>  
              <!--      <li><a href="listuser">Excluir Usuário</a></li>-->
                </ul>
              </li>
              <li><a href="/auth/logout">SAIR</a></li>
            </ul>
          </div><!--/.nav-collapse -->
      </div>
    </div>

   <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
         <h4 id="relogio"></h4>
      <h2>COMPARING </h2>
      <h4>Relação dos usuários cadastrados</h4>
        </div>
    </div>

    <div class="container">
           <div class="row">						
		      	<!-- Text input-->
						  <div class="bs-docs-example">
						  <div class="table-responsive">
				            <table class="table table-striped" id="videos">
				              <thead>
				               <tr>
				                   			<th>#</th>  
									<th style="cursor:pointer">Login</th>
									<th style="cursor:pointer">Nome do Usuário</th>
									<th style="cursor:pointer">Empresa</th>
									<th style="cursor:pointer">Nivel de Permissão</th>
									<th>Excluir</th>
				                </tr>
				              </thead>
				              <tbody>
				              
				              <?php foreach ($this->users as $user): ?>
								<tr>
								 	<td class="rownums"></td>
									<td><?php echo $this->escape($user->login); ?></td>
									<td><?php echo $this->escape($user->nome_usuario); ?></td>
									<td><?php echo $this->escape($user->clientes_id); ?></td>
									<td><?php echo $this->escape($user->perfil_id); ?></td>
		<td>																	
       
            <a href="<?php echo $this->url(array('controller'=>'admin','action'=>'deleteuser', 'id'=>$user->id)); ?>"><img src="/image/delete.png" width="16" height="16" /></a>
          </td>
								</tr>
								<?php endforeach; ?>
				              </tbody>
				            </table>
				            			            
								  <div id="pager" class="pager">
								    <form class="form-horizontal" role="form">
									<fieldset>
									<!-- Select Basic -->
									<div class="control-group">	
									  <div class="controls">
									  	<label class="control-label" for="selectbasic">Registros</label>												
										<select  id="selectbasic" name="selectbasic"  class="input-mini pagesize">
										<option selected="selected" value="1000">TODOS</option>
										</select>
									  </div>
									</div>
										
										 <!-- Text input-->
								
									</fieldset>
									</form>
								</div>	
								               
				 			</div>
				    		</div>
		</div>		          
      <hr>

      <footer>
    <p>Você está em um ambiente seguro. Todos os seus dados estão protegidos.</p>
  <p> Viterativa - Web e Vídeo Conteúdo CNPJ: XXXXXXXX</p>
       <p>Comparing V1.0 &copy; 2014 - Todos os direitos reservados.</p>
      </footer>
    </div> <!-- /container -->
    <!--  
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/js/jquery-1.11.1.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/jquery1.5.1.js"></script>
    <script src="/js/jquery.tablesorter.min.js"></script>
    <script src="/jss/jquery.tablesorter.pager.js"></script>
    <script src="/jss/efeito.js"></script>
    <script src="/js/relogio.js"></script> 
    <script src="/js/comparing.js"></script>
  </body>
</html>
